name:                sake
version:             0.1.0.0
github:              "konn/sake"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md
- data/*.mustache

flags:
  example:
    manual:  false
    default: false
    description: Whether build example executable or not

# Metadata used when publishing your package
synopsis:            A simple and extensible static site generator built on top of Shake.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Please see the README on Github at <https://github.com/konn/sake#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-icu
- wai-app-static
- warp
- contravariant
- data-default
- doclayout
- filepath
- megaparsec
- pandoc
- shake
- stache
- store

ghc-options:
- -Wall

library:
  dependencies:
  - aeson
  - blaze-html
  - bytestring
  - containers
  - cryptohash-sha256
  - directory
  - doctemplates
  - hashable
  - mtl
  - operational
  - pandoc-types
  - reflection
  - shakespeare
  - tagsoup
  - template-haskell
  - time
  - unordered-containers
  - wai
  - yaml

  source-dirs: src
  other-modules:
  - Web.Sake.Utils
  default-extensions:
  - OverloadedStrings
  - DeriveAnyClass
  - DeriveGeneric
  - MultiParamTypeClasses

executables:
  site:
    when:
    - condition: flag(example)
      then:
        buildable: true
      else:
        buildable: false
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - sake
    - shake
    - text
