resolver: lts-14.14

packages:
  - .

extra-deps:
  - git: git@github.com:konn/latex-crossref.git
    commit: 79c9ac25f2bb1bfcb40f261a0ea4ffaefd295067

extra-lib-dirs:
  - /usr/local/opt/icu4c/lib

extra-include-dirs:
  - /usr/local/opt/icu4c/include
# build:
#   haddock: true
#   haddock-deps: false
